CREATE PROCEDURE fz_LogShipmateConsignmentRequestResponse
@Success bit,
@ErrorMessage varchar(500),
@ReqServiceID int,
@ReqRemittanceID int,
@ReqConsignmentReference varchar(50),
@ReqServiceKey varchar(25),
@ReqName varchar(50),
@ReqLine1 varchar(250),
@ReqCity varchar(40),
@ReqPostcode varchar(10),
@ReqCountry varchar(40),
@ReqReference varchar(60),
@ReqWeight int,
@ReqWidth int,
@ReqLength int,
@ReqDepth int,
@ResMessage varchar(500) = NULL,
@ResConsignmentReference varchar(100) = NULL,
@ResParcelReference varchar(100) = NULL,
@ResCarrier varchar(100) = NULL,
@ResServiceName varchar(100) = NULL,
@ResTrackingReference varchar(100) = NULL,
@ResCreatedBy varchar(100) = NULL,
@ResCreatedWith varchar(100) = NULL,
@ResCreatedAt datetime = NULL,
@ResDeliveryName varchar(100) = NULL,
@ResLine1 varchar(50) = NULL,
@ResLine2 varchar(50) = NULL,
@ResLine3 varchar(50) = NULL,
@ResCity varchar(40) = NULL,
@ResCounty varchar(40) = NULL,
@ResPostcode varchar(10) = NULL,
@ResCountry varchar(40) = NULL,
@ResMediaURL varchar(250) = NULL,
@ResMediaGUID varchar(50) = NULL
AS
DECLARE @ID int

INSERT INTO ShipmateConsignmentCreation
(
  DateCreated,
  Success,
  ErrorMessage,
  ReqServiceID,
  ReqRemittanceID,
  ReqConsignmentReference,
  ReqServiceKey,
  ReqName,
  ReqLine1,
  ReqCity,
  ReqPostcode,
  ReqCountry,
  ReqReference,
  ReqWeight,
  ReqWidth,
  ReqLength,
  ReqDepth,
  ResMessage,
  ResConsignmentReference,
  ResParcelReference,
  ResCarrier,
  ResServiceName,
  ResTrackingReference,
  ResCreatedBy,
  ResCreatedWith,
  ResCreatedAt,
  ResDeliveryName,
  ResLine1,
  ResLine2,
  ResLine3,
  ResCity,
  ResCounty,
  ResPostcode,
  ResCountry,
  ResMediaURL,
  ResMediaGUID
)
VALUES
(
  getdate(),
  @Success,
  @ErrorMessage,
  @ReqServiceID,
  @ReqRemittanceID,
  @ReqConsignmentReference,
  @ReqServiceKey,
  @ReqName,
  @ReqLine1,
  @ReqCity,
  @ReqPostcode,
  @ReqCountry,
  @ReqReference,
  @ReqWeight,
  @ReqWidth,
  @ReqLength,
  @ReqDepth,
  @ResMessage,
  @ResConsignmentReference,
  @ResParcelReference,
  @ResCarrier,
  @ResServiceName,
  @ResTrackingReference,
  @ResCreatedBy,
  @ResCreatedWith,
  @ResCreatedAt,
  @ResDeliveryName,
  @ResLine1,
  @ResLine2,
  @ResLine3,
  @ResCity,
  @ResCounty,
  @ResPostcode,
  @ResCountry,
  @ResMediaURL,
  @ResMediaGUID
)

SELECT TOP 1 @ID = ID
FROM ShipmateConsignmentCreation
ORDER BY ID desc

return @ID