CREATE PROCEDURE fz_GetShipmateConsignmentDetails
@TrackingReference varchar(50)
AS
SELECT TOP 1
  ISNULL(ResTrackingReference, '') AS 'ResTrackingReference',
  LABEL_CREATED,
  MANIFESTED,
  COLLECTED,
  IN_TRANSIT,
  DELIVERED,
  DELIVERY_FAILED,
  ReqServiceID,
  ReqRemittanceID,
  ISNULL(ReqConsignmentReference, '') AS 'ReqConsignmentReference',
  ISNULL(ReqServiceKey, '') AS 'ReqServiceKey',
  ISNULL(ReqCollectionFromName, '') AS 'ReqCollectionFromName',
  ISNULL(ReqCollectionFromLine1, '') AS 'ReqCollectionFromLine1',
  ISNULL(ReqCollectionFromLine2, '') AS 'ReqCollectionFromLine2',
  ISNULL(ReqCollectionFromLine3, '') AS 'ReqCollectionFromLine3',
  ISNULL(ReqCollectionFromCompanyName, '') AS 'ReqCollectionFromCompanyName',
  ISNULL(ReqCollectionFromTelephone, '') AS 'ReqCollectionFromTelephone',
  ISNULL(ReqCollectionFromEmailAddress, '') AS 'ReqCollectionFromEmailAddress',
  ISNULL(ReqCollectionFromCity, '') AS 'ReqCollectionFromCity',
  ISNULL(ReqCollectionFromPostcode, '') AS 'ReqCollectionFromPostcode',
  ISNULL(ReqCollectionFromCountry, '') AS 'ReqCollectionFromCountry',
  ISNULL(ReqDeliveryToName, '') AS 'ReqDeliveryToName',
  ISNULL(ReqDeliveryToLine1, '') AS 'ReqDeliveryToLine1',
  ISNULL(ReqDeliveryToLine2, '') AS 'ReqDeliveryToLine2',
  ISNULL(ReqDeliveryToLine3, '') AS 'ReqDeliveryToLine3',
  ISNULL(ReqDeliveryToCompanyName, '') AS 'ReqDeliveryToCompanyName',
  ISNULL(ReqDeliveryToTelephone, '') AS 'ReqDeliveryToTelephone',
  ISNULL(ReqDeliveryToEmailAddress, '') AS 'ReqDeliveryToEmailAddress',
  ISNULL(ReqDeliveryToCity, '') AS 'ReqDeliveryToCity',
  ISNULL(ReqDeliveryToPostcode, '') AS 'ReqDeliveryToPostcode',
  ISNULL(ReqDeliveryToCountry, '') AS 'ReqDeliveryToCountry',
  ISNULL(ReqParcelReference, '') AS 'ReqParcelReference',
  ReqParcelWeight,
  ReqParcelWidth,
  ReqParcelLength,
  ReqParcelDepth,
  ISNULL(ResConsignmentReference, '') AS 'ResConsignmentReference',
  ISNULL(ResParcelReference, '') AS 'ResParcelReference',
  ISNULL(ResCarrier, '') AS 'ResCarrier',
  ISNULL(ResServiceName, '') AS 'ResServiceName',
  ISNULL(ResCreatedBy, '') AS 'ResCreatedBy',
  ISNULL(ResCreatedWith, '') AS 'ResCreatedWith',
  ResCreatedAt,
  ISNULL(ResMediaGUID, '') AS 'ResMediaGUID'
FROM
  ShipmateConsignmentCreation
WHERE
  ResTrackingReference = @TrackingReference