CREATE PROCEDURE fz_LogShipmateConsignmentRequestResponse
@Success bit,
@ErrorMessage varchar(500),
@ReqServiceID int,
@ReqRemittanceID int,
@ReqConsignmentReference varchar(50),
@ReqServiceKey varchar(25),
@ReqName varchar(50),
@ReqLine1 varchar(250),
@ReqCity varchar(40),
@ReqPostcode varchar(10),
@ReqCountry varchar(40),
@ReqReference varchar(60),
@ReqWeight int,
@ReqWidth int,
@ReqLength int,
@ReqDepth int,
@RepMessage varchar(500) = NULL,
@RepConsignmentReference varchar(100) = NULL,
@RepParcelReference varchar(100) = NULL,
@RepCarrier varchar(100) = NULL,
@RepServiceName varchar(100) = NULL,
@RepTrackingReference varchar(100) = NULL,
@RepCreatedBy varchar(100) = NULL,
@RepCreatedWith varchar(100) = NULL,
@RepCreatedAt datetime = NULL,
@RepDeliveryName varchar(100) = NULL,
@RepLine1 varchar(50) = NULL,
@RepLine2 varchar(50) = NULL,
@RepLine3 varchar(50) = NULL,
@RepCity varchar(40) = NULL,
@RepCounty varchar(40) = NULL,
@RepPostcode varchar(10) = NULL,
@RepCountry varchar(40) = NULL,
@RepPdf varchar(max) = NULL,
@RepZpl varchar(max) = NULL,
@RepPng varchar(max) = NULL
AS
DECLARE @ID int

INSERT INTO ShipmateConsignmentCreation
(
  DateCreated,
  Success,
  ErrorMessage,
  ReqServiceID,
  ReqRemittanceID,
  ReqConsignmentReference,
  ReqServiceKey,
  ReqName,
  ReqLine1,
  ReqCity,
  ReqPostcode,
  ReqCountry,
  ReqReference,
  ReqWeight,
  ReqWidth,
  ReqLength,
  ReqDepth,
  RepMessage,
  RepConsignmentReference,
  RepParcelReference,
  RepCarrier,
  RepServiceName,
  RepTrackingReference,
  RepCreatedBy,
  RepCreatedWith,
  RepCreatedAt,
  RepDeliveryName,
  RepLine1,
  RepLine2,
  RepLine3,
  RepCity,
  RepCounty,
  RepPostcode,
  RepCountry,
  RepPdf,
  RepZpl,
  RepPng
)
VALUES
(
  getdate(),
  @Success,
  @ErrorMessage,
  @ReqServiceID,
  @ReqRemittanceID,
  @ReqConsignmentReference,
  @ReqServiceKey,
  @ReqName,
  @ReqLine1,
  @ReqCity,
  @ReqPostcode,
  @ReqCountry,
  @ReqReference,
  @ReqWeight,
  @ReqWidth,
  @ReqLength,
  @ReqDepth,
  @RepMessage,
  @RepConsignmentReference,
  @RepParcelReference,
  @RepCarrier,
  @RepServiceName,
  @RepTrackingReference,
  @RepCreatedBy,
  @RepCreatedWith,
  @RepCreatedAt,
  @RepDeliveryName,
  @RepLine1,
  @RepLine2,
  @RepLine3,
  @RepCity,
  @RepCounty,
  @RepPostcode,
  @RepCountry,
  @RepPdf,
  @RepZpl,
  @RepPng
)

SELECT TOP 1 @ID = ID
FROM ShipmateConsignmentCreation
ORDER BY ID desc

return @ID