CREATE PROCEDURE fz_GetShipmateConsignmentDetails
@TrackingReference varchar(50)
AS
SELECT TOP 1
  DateTimeRowInserted,
  SendRequestSuccess,
  ISNULL(SendRequestErrorMessage, ''),
  ISNULL(ResTrackingReference, ''),
  LABEL_CREATED,
  MANIFESTED,
  COLLECTED,
  IN_TRANSIT,
  DELIVERED,
  DELIVERY_FAILED,
  ISNULL(ReqServiceID, 0),
  ISNULL(ReqRemittanceID, 0),
  ISNULL(ReqConsignmentReference, ''),
  ISNULL(ReqServiceKey, ''),
  ISNULL(ReqCollectionFromName, ''),
  ISNULL(ReqCollectionFromLine1, ''),
  ISNULL(ReqCollectionFromLine2, ''),
  ISNULL(ReqCollectionFromLine3, ''),
  ISNULL(ReqCollectionFromCompanyName, ''),
  ISNULL(ReqCollectionFromTelephone, ''),
  ISNULL(ReqCollectionFromEmailAddress, ''),
  ISNULL(ReqCollectionFromCity, ''),
  ISNULL(ReqCollectionFromPostcode, ''),
  ISNULL(ReqCollectionFromCountry, ''),
  ISNULL(ReqDeliveryToName, ''),
  ISNULL(ReqDeliveryToLine1, ''),
  ISNULL(ReqDeliveryToLine2, ''),
  ISNULL(ReqDeliveryToLine3, ''),
  ISNULL(ReqDeliveryToCompanyName, ''),
  ISNULL(ReqDeliveryToTelephone, ''),
  ISNULL(ReqDeliveryToEmailAddress, ''),
  ISNULL(ReqDeliveryToCity, ''),
  ISNULL(ReqDeliveryToPostcode, ''),
  ISNULL(ReqDeliveryToCountry, ''),
  ISNULL(ReqParcelReference, ''),
  ISNULL(ReqParcelWeight, 0),
  ISNULL(ReqParcelWidth, 0),
  ISNULL(ReqParcelLength, 0),
  ISNULL(ReqParcelDepth, 0),
  ISNULL(ResMessage, ''),
  ISNULL(ResConsignmentReference, ''),
  ISNULL(ResParcelReference, ''),
  ISNULL(ResCarrier, ''),
  ISNULL(ResServiceName, ''),
  ISNULL(ResCreatedBy, ''),
  ISNULL(ResCreatedWith, ''),
  ResCreatedAt,
  ISNULL(ResMediaURL, ''),
  ISNULL(ResMediaGUID, '')
FROM
  ShipmateConsignmentCreation
WHERE
  ResTrackingReference = @TrackingReference