CREATE PROCEDURE fz_LogShipmateConsignmentRequestResponse
@SendRequestSuccess bit,
@SendRequestErrorMessage varchar(500),
@ResTrackingReference varchar(100),
@LabelCreated datetime,
@ReqServiceID int,
@ReqRemittanceID int,
@ReqConsignmentReference varchar(50),
@ReqServiceKey varchar(25),
@ReqCollectionFromName varchar(50),
@ReqCollectionFromLine1 varchar(50),
@ReqCollectionFromLine2 varchar(50),
@ReqCollectionFromLine3 varchar(50),
@ReqCollectionFromCompanyName varchar(50),
@ReqCollectionFromTelephone varchar(25),
@ReqCollectionFromEmailAddress varchar(50),
@ReqCollectionFromCity varchar(50),
@ReqCollectionFromPostcode [varchar](10),
@ReqCollectionFromCountry [varchar](50),
@ReqDeliverToName varchar(50),
@ReqDeliverToLine1 varchar(50),
@ReqDeliverToLine2 varchar(50),
@ReqDeliverToLine3 varchar(50),
@ReqDeliverToCompanyName varchar(50),
@ReqDeliverToTelephone varchar(25),
@ReqDeliverToEmailAddress varchar(50),
@ReqDeliverToCity varchar(50),
@ReqDeliverToPostcode varchar(10),
@ReqDeliverToCountry varchar(50),
@ReqParcelReference varchar(50),
@ReqParcelWeight int,
@ReqParcelWidth int,
@ReqParcelLength int,
@ReqParcelDepth int,
@ResMessage varchar(500) = NULL,
@ResConsignmentReference varchar(100) = NULL,
@ResParcelReference varchar(100) = NULL,
@ResCarrier varchar(100) = NULL,
@ResServiceName varchar(100) = NULL,
@ResCreatedBy varchar(100) = NULL,
@ResCreatedWith varchar(100) = NULL,
@ResCreatedAt datetime = NULL,
@ResMediaURL varchar(250) = NULL,
@ResMediaGUID varchar(50) = NULL
AS
DECLARE @ID int

INSERT INTO ShipmateConsignmentCreation
(
  DateTimeRowInserted,
  SendRequestSuccess,
  SendRequestErrorMessage,
  ResTrackingReference,
  LABEL_CREATED,
  ReqServiceID,
  ReqRemittanceID,
  ReqConsignmentReference,
  ReqServiceKey,
  ReqCollectionFromName,
  ReqCollectionFromLine1,
  ReqCollectionFromLine2,
  ReqCollectionFromLine3,
  ReqCollectionFromCompanyName,
  ReqCollectionFromTelephone,
  ReqCollectionFromEmailAddress,
  ReqCollectionFromCity,
  ReqCollectionFromPostcode,
  ReqCollectionFromCountry,
  ReqDeliverToName,
  ReqDeliverToLine1,
  ReqDeliverToLine2,
  ReqDeliverToLine3,
  ReqDeliverToCompanyName,
  ReqDeliverToTelephone,
  ReqDeliverToEmailAddress,
  ReqDeliverToCity,
  ReqDeliverToPostcode,
  ReqDeliverToCountry,
  ReqParcelReference,
  ReqParcelWeight,
  ReqParcelWidth,
  ReqParcelLength,
  ReqParcelDepth,
  ResMessage,
  ResConsignmentReference,
  ResParcelReference,
  ResCarrier,
  ResServiceName,
  ResCreatedBy,
  ResCreatedWith,
  ResCreatedAt,
  ResMediaURL,
  ResMediaGUID
)
VALUES
(
  getdate(),
  @SendRequestSuccess,
  @SendRequestErrorMessage,
  @ResTrackingReference,
  @LabelCreated,
  @ReqServiceID,
  @ReqRemittanceID,
  @ReqConsignmentReference,
  @ReqServiceKey,
  @ReqCollectionFromName,
  @ReqCollectionFromLine1,
  @ReqCollectionFromLine2,
  @ReqCollectionFromLine3,
  @ReqCollectionFromCompanyName,
  @ReqCollectionFromTelephone,
  @ReqCollectionFromEmailAddress,
  @ReqCollectionFromCity,
  @ReqCollectionFromPostcode,
  @ReqCollectionFromCountry,
  @ReqDeliverToName,
  @ReqDeliverToLine1,
  @ReqDeliverToLine2,
  @ReqDeliverToLine3,
  @ReqDeliverToCompanyName,
  @ReqDeliverToTelephone,
  @ReqDeliverToEmailAddress,
  @ReqDeliverToCity,
  @ReqDeliverToPostcode,
  @ReqDeliverToCountry,
  @ReqParcelReference,
  @ReqParcelWeight,
  @ReqParcelWidth,
  @ReqParcelLength,
  @ReqParcelDepth,
  @ResMessage,
  @ResConsignmentReference,
  @ResParcelReference,
  @ResCarrier,
  @ResServiceName,
  @ResCreatedBy,
  @ResCreatedWith,
  @ResCreatedAt,
  @ResMediaURL,
  @ResMediaGUID
)

SELECT TOP 1 @ID = ID
FROM ShipmateConsignmentCreation
ORDER BY ID desc

return @ID