--Ran ok 2019-05-03 kl. 16:54
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Triggers_Bak03May2019](
	[TRIGGERID] [int] NOT NULL,
	[TRIGGERNAME] [varchar](50) NULL,
	[TRIGGERSQL] [text] NULL,
	[TRIGGERCHILDSQL] [text] NULL,
	[TRIGGERFIELDNAME] [varchar](50) NULL,
	[TRIGGERINTERVAL] [smallint] NULL,
	[TRIGGERDATE] [datetime] NULL,
	[TRIGGERTIME] [varchar](5) NULL,
	[MESSAGEID] [int] NULL,
	[TRIGGERSETPOSTED] [bit] NULL,
	[SAEDISourceId] [nvarchar](11) NULL,
	[SMTPHostID] [int] NULL
)
GO

SET ANSI_PADDING OFF
GO

INSERT INTO Triggers_Bak03May2019
(
	[TRIGGERID],
	[TRIGGERNAME],
	[TRIGGERSQL],
	[TRIGGERCHILDSQL],
	[TRIGGERFIELDNAME],
	[TRIGGERINTERVAL],
	[TRIGGERDATE],
	[TRIGGERTIME],
	[MESSAGEID],
	[TRIGGERSETPOSTED],
	[SAEDISourceId],
	[SMTPHostID]
)
SELECT
	[TRIGGERID],
	[TRIGGERNAME],
	[TRIGGERSQL],
	[TRIGGERCHILDSQL],
	[TRIGGERFIELDNAME],
	[TRIGGERINTERVAL],
	[TRIGGERDATE],
	[TRIGGERTIME],
	[MESSAGEID],
	[TRIGGERSETPOSTED],
	[SAEDISourceId],
	[SMTPHostID]
FROM
   [Triggers]