CREATE VIEW NumberOfJobs
AS
SELECT TOP 1000000
  CAST(YEAR(CALLDATETIME) AS varchar(4)) + CASE WHEN MONTH(CALLDATETIME) < 10 THEN '-0' ELSE '-' END + CAST(MONTH(CALLDATETIME) AS varchar(2)) AS 'Year-Month', 
  COUNT(*) AS 'Count'
FROM
  [dbo].[service]
WHERE
  CALLDATETIME IS NOT NULL AND CALLDATETIME >= '2017-05-01 00:00:00.000'
GROUP BY
  CAST(YEAR(CALLDATETIME) AS varchar(4)) + CASE WHEN MONTH(CALLDATETIME) < 10 THEN '-0' ELSE '-' END + CAST(MONTH(CALLDATETIME) AS varchar(2)) 
ORDER BY
  CAST(YEAR(CALLDATETIME) AS varchar(4)) + CASE WHEN MONTH(CALLDATETIME) < 10 THEN '-0' ELSE '-' END + CAST(MONTH(CALLDATETIME) AS varchar(2))